"use client";
import "../profile-reference.css";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {AppShell} from "@/components/AppShell";
import {useAuth} from "@/components/AuthProvider";
import {getSupabase} from "@/lib/supabase";
import {Menu,Church,CalendarDays,Package,Heart,HandCoins,CircleHelp,ChevronRight,Settings,BookOpen,Bus} from "lucide-react";

type Stats={favorites:number;orders:number;bookings:number;moments:number};
type Parish={name:string;city?:string|null;state?:string|null};
export default function Perfil(){
 const {user,profile,loading,signOut}=useAuth();const router=useRouter();const [stats,setStats]=useState<Stats>({favorites:0,orders:0,bookings:0,moments:0});const [parish,setParish]=useState<Parish|null>(null);
 useEffect(()=>{if(loading)return;if(!user){router.replace("/entrar?next=/perfil");return}const s=getSupabase();Promise.all([s.from("favorites").select("entity_id",{count:"exact",head:true}).eq("user_id",user.id),s.from("orders").select("id",{count:"exact",head:true}).eq("user_id",user.id),s.from("bookings").select("id",{count:"exact",head:true}).eq("user_id",user.id),s.from("devotional_completions").select("devotional_id",{count:"exact",head:true}).eq("user_id",user.id),profile?.primary_parish_id?s.from("parishes").select("name,city,state").eq("id",profile.primary_parish_id).maybeSingle():Promise.resolve({data:null}) as Promise<{data:null}>]).then(([a,b,c,d,e])=>{setStats({favorites:a.count||0,orders:b.count||0,bookings:c.count||0,moments:d.count||0});setParish((e.data||null) as Parish|null)})},[user,profile,loading,router]);
 if(loading||!user)return <AppShell hideHeader><div className="card profile-ref-loading">Carregando…</div></AppShell>;
 const name=profile?.full_name||"Seu perfil";const initials=name.split(" ").slice(0,2).map((x:string)=>x[0]).join("").toUpperCase();
 const rows=[{label:"Minha Igreja",detail:parish?`${parish.name} • ${parish.city||""}`:"Escolher comunidade",href:"/igreja",icon:Church},{label:"Meus Eventos",detail:"Inscrições e próximos encontros",href:"/eventos",icon:CalendarDays},{label:"Minhas Peregrinações",detail:"Reservas e destinos salvos",href:"/peregrinacoes",icon:Bus},{label:"Meus Pedidos",detail:"Compras e acompanhamento",href:"/pedidos",icon:Package},{label:"Meus Favoritos",detail:"Conteúdos, produtos e experiências",href:"/favoritos",icon:Heart},{label:"Minhas Doações",detail:"Histórico de contribuições",href:"/doacoes",icon:HandCoins},{label:"Configurações",detail:"Conta, privacidade e preferências",href:"/configuracoes",icon:Settings},{label:"Ajuda e Suporte",detail:"Fale com o Vinde",href:"/ajuda",icon:CircleHelp}];
 return <AppShell hideHeader><div className="profile-ref"><div className="profile-ref-top"><div><span className="product-kicker">MINHA VIDA NO VINDE</span><h1>Meu Perfil</h1></div><Link href="/menu" className="profile-ref-settings" aria-label="Abrir menu"><Menu/></Link></div><div className="profile-ref-user"><div className="profile-ref-avatar">{initials}</div><div><h2>{name}</h2><p className="profile-ref-email">{user.email}</p><Link href="/configuracoes" className="profile-ref-edit">Editar perfil</Link></div></div><div className="profile-summary"><div className="profile-stat"><strong>{stats.moments}</strong><small>momentos concluídos</small></div><div className="profile-stat"><strong>{stats.favorites}</strong><small>favoritos</small></div><div className="profile-stat"><strong>{stats.bookings}</strong><small>viagens/reservas</small></div></div><div className="trust-strip"><BookOpen/><div><strong>Sua caminhada, não uma competição.</strong><p>O histórico existe para ajudar você a perceber constância e guardar o que fez sentido — sem ranking entre pessoas.</p></div></div><div className="profile-ref-menu">{rows.map(({label,detail,href,icon:Icon})=><Link href={href} className="profile-ref-row" key={label}><span className="profile-ref-icon"><Icon/></span><span style={{flex:1}}><b style={{display:"block"}}>{label}</b><small className="muted">{detail}</small></span><ChevronRight/></Link>)}</div><button className="profile-ref-signout" onClick={async()=>{await signOut();router.push("/")}}>Sair da conta</button></div></AppShell>;
}
