"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";import {useAuth} from "@/components/AuthProvider";import {getSupabase} from "@/lib/supabase";
const topics=["Momento Diário","Minha Paróquia","Eventos","Peregrinações","Livros","Campanhas"];
export default function Onboarding(){const {user,loading,refreshProfile}=useAuth();const router=useRouter();const [step,setStep]=useState(1);const [city,setCity]=useState("Piumhi");const [state,setState]=useState("MG");const [parishes,setParishes]=useState<any[]>([]);const [parishId,setParishId]=useState("");const [prefs,setPrefs]=useState<string[]>(["Momento Diário","Minha Paróquia","Eventos"]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!loading&&!user)router.replace("/entrar?next=/onboarding")},[user,loading,router]);
 async function findParishes(){setBusy(true);const {data,error}=await getSupabase().from("parishes").select("id,name,city,state,verified").ilike("city",city.trim()).ilike("state",state.trim()).order("verified",{ascending:false}).order("name");setParishes(data||[]);if(data?.[0])setParishId(data[0].id);setMessage(error?"Não foi possível buscar as paróquias.":data?.length?"":"Nenhuma paróquia cadastrada para esta cidade ainda.");setBusy(false);setStep(2)}
 async function finish(){if(!user)return;setBusy(true);const s=getSupabase();const preferenceMap=Object.fromEntries(topics.map(t=>[t,prefs.includes(t)]));const {error}=await s.from("profiles").upsert({id:user.id,city:city.trim(),state:state.trim().toUpperCase(),primary_parish_id:parishId||null,onboarding_completed:true,preferences:preferenceMap},{onConflict:"id"});if(!error&&parishId){await s.from("parish_members").update({is_primary:false}).eq("user_id",user.id);await s.from("parish_members").upsert({parish_id:parishId,user_id:user.id,role:"follower",is_primary:true},{onConflict:"parish_id,user_id"})}if(error){setMessage(error.message);setBusy(false);return}await refreshProfile();router.push("/")}
 if(loading||!user)return <main className="shell narrow"><div className="card onboarding">Preparando sua conta…</div></main>;
 return <main className="shell narrow"><Link href="/" className="brand"><small>PLATAFORMA CATÓLICA</small>Ágora Fide</Link><div className="card onboarding"><div className="eyebrow">Passo {step} de 3</div>{step===1&&<><h1>Vamos começar pela sua comunidade.</h1><p className="muted">Informe onde você participa da vida paroquial.</p><label className="field"><span>Cidade</span><input value={city} onChange={e=>setCity(e.target.value)}/></label><label className="field"><span>Estado</span><input value={state} maxLength={2} onChange={e=>setState(e.target.value)}/></label></>}{step===2&&<><h1>Qual é a sua paróquia?</h1><p className="muted">Você poderá trocar depois.</p>{parishes.map(p=><button type="button" className={`choice choice-button ${parishId===p.id?"active-choice":""}`} onClick={()=>setParishId(p.id)} key={p.id}><span>{p.name}<small>{p.city} • {p.state}</small></span><span>{parishId===p.id?"✓":""}</span></button>)}{message&&<p className="muted">{message}</p>}<button className={`choice choice-button ${!parishId?"active-choice":""}`} onClick={()=>setParishId("")}>Ainda não encontrei minha paróquia</button></>}{step===3&&<><h1>O que você quer acompanhar?</h1><div className="chips">{topics.map(t=><button type="button" key={t} className={`pill chip-button ${prefs.includes(t)?"selected":""}`} onClick={()=>setPrefs(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}>{prefs.includes(t)?"✓ ":""}{t}</button>)}</div><p className="muted">Essas preferências podem ser alteradas no perfil.</p></>}<div className="actions">{step>1&&<button className="cta secondary" onClick={()=>setStep(step-1)}>Voltar</button>}{step===1?<button className="cta" disabled={busy||!city||!state} onClick={findParishes}>{busy?"Buscando…":"Continuar"}</button>:step===2?<button className="cta" onClick={()=>setStep(3)}>Continuar</button>:<button className="cta" disabled={busy} onClick={finish}>{busy?"Salvando…":"Entrar no app"}</button>}</div></div></main>}
