"use client";
import "./onboarding.css";import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {useAuth} from "@/components/AuthProvider";import {getSupabase} from "@/lib/supabase";
const topics=["Momento Diário","Minha Paróquia","Eventos","Peregrinações","Livros","Campanhas"];
export default function Onboarding(){const {user,loading,refreshProfile}=useAuth();const router=useRouter();const [step,setStep]=useState(1);const [city,setCity]=useState("Piumhi");const [state,setState]=useState("MG");const [parishes,setParishes]=useState<any[]>([]);const [parishId,setParishId]=useState("");const [prefs,setPrefs]=useState<string[]>(["Momento Diário","Minha Paróquia","Eventos"]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!loading&&!user)router.replace("/entrar?next=/onboarding")},[user,loading,router]);
 async function findParishes(){setBusy(true);const {data,error}=await getSupabase().from("parishes").select("id,name,city,state,verified").ilike("city",city.trim()).ilike("state",state.trim()).order("verified",{ascending:false}).order("name");setParishes(data||[]);if(data?.[0])setParishId(data[0].id);setMessage(error?"Não foi possível buscar as paróquias.":data?.length?"":"Nenhuma paróquia cadastrada para esta cidade ainda.");setBusy(false);setStep(2)}
 async function finish(){if(!user)return;setBusy(true);const s=getSupabase();const preferenceMap=Object.fromEntries(topics.map(t=>[t,prefs.includes(t)]));const {error}=await s.from("profiles").upsert({id:user.id,city:city.trim(),state:state.trim().toUpperCase(),primary_parish_id:parishId||null,onboarding_completed:true,preferences:preferenceMap},{onConflict:"id"});if(!error&&parishId){await s.from("parish_members").update({is_primary:false}).eq("user_id",user.id);await s.from("parish_members").upsert({parish_id:parishId,user_id:user.id,role:"follower",is_primary:true},{onConflict:"parish_id,user_id"})}if(error){setMessage(error.message);setBusy(false);return}await refreshProfile();router.push("/")}
 if(loading||!user)return <main className="vinde-loading">Preparando sua experiência no Vinde…</main>;
 return <main className="vinde-onboarding"><section className="vinde-onboarding-shell"><div className="vinde-onboarding-brand"><span>✣</span>Vinde</div><div className="vinde-onboarding-progress"><i className="active"/><i className={step>=2?"active":""}/><i className={step>=3?"active":""}/></div><div className="vinde-onboarding-card"><div className="vinde-onboarding-kicker">Passo {step} de 3</div>{step===1&&<><h1>Vamos começar pela sua comunidade.</h1><p>Conte onde você vive sua fé. Isso ajuda o Vinde a mostrar horários, avisos, eventos e conteúdos mais próximos de você.</p><label className="vinde-onboarding-field"><span>Cidade</span><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Sua cidade"/></label><label className="vinde-onboarding-field"><span>Estado</span><input value={state} maxLength={2} onChange={e=>setState(e.target.value)} placeholder="UF"/></label></>}{step===2&&<><h1>Qual é a sua paróquia?</h1><p>Escolha sua comunidade principal. Você poderá alterar isso depois no seu perfil.</p><div className="vinde-parish-list">{parishes.map(p=><button type="button" className={`vinde-parish-choice ${parishId===p.id?"active":""}`} onClick={()=>setParishId(p.id)} key={p.id}><span><strong>{p.name}</strong><small>{p.city} • {p.state}</small></span><span className="vinde-check">{parishId===p.id?"✓":""}</span></button>)}<button type="button" className={`vinde-parish-choice vinde-no-parish ${!parishId?"active":""}`} onClick={()=>setParishId("")}><span><strong>Ainda não encontrei minha paróquia</strong><small>Você pode continuar e configurar depois.</small></span><span className="vinde-check">{!parishId?"✓":""}</span></button></div>{message&&<p className="vinde-onboarding-message">{message}</p>}</>}{step===3&&<><h1>O que você quer acompanhar?</h1><p>Escolha o que mais combina com sua rotina de fé. O Vinde vai usar isso para personalizar sua experiência.</p><div className="vinde-topic-grid">{topics.map(t=><button type="button" key={t} className={`vinde-topic ${prefs.includes(t)?"selected":""}`} onClick={()=>setPrefs(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}><span>{t}</span><b>{prefs.includes(t)?"✓":"+"}</b></button>)}</div></>}<div className="vinde-onboarding-actions">{step>1&&<button className="vinde-secondary" onClick={()=>setStep(step-1)}>Voltar</button>}{step===1?<button className="vinde-primary" disabled={busy||!city||!state} onClick={findParishes}>{busy?"Buscando…":"Continuar"}</button>:step===2?<button className="vinde-primary" onClick={()=>setStep(3)}>Continuar</button>:<button className="vinde-primary" disabled={busy} onClick={finish}>{busy?"Salvando…":"Entrar no Vinde"}</button>}</div></div><p className="vinde-onboarding-note">Vinde · Fé que acompanha você.</p></section></main>}
