"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Church,BookOpen,CalendarDays,Bus,Heart,ShoppingBag,MapPin} from "lucide-react";
import {useAuth} from "@/components/AuthProvider";
import {getSupabase} from "@/lib/supabase";

type Parish={id:string;name:string;city:string;state:string;verified?:boolean|null};
const topics=[
 {label:"Momento Diário",icon:BookOpen},{label:"Minha Paróquia",icon:Church},{label:"Eventos",icon:CalendarDays},{label:"Peregrinações",icon:Bus},{label:"Livros",icon:ShoppingBag},{label:"Campanhas",icon:Heart}
];
export default function Onboarding(){
 const {user,loading,refreshProfile}=useAuth();const router=useRouter();const [step,setStep]=useState(1);const [city,setCity]=useState("Piumhi");const [state,setState]=useState("MG");const [parishes,setParishes]=useState<Parish[]>([]);const [parishId,setParishId]=useState("");const [prefs,setPrefs]=useState<string[]>(["Momento Diário","Minha Paróquia","Eventos"]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(!loading&&!user)router.replace("/entrar?next=/onboarding")},[user,loading,router]);
 async function findParishes(){setBusy(true);const {data,error}=await getSupabase().from("parishes").select("id,name,city,state,verified").ilike("city",city.trim()).ilike("state",state.trim()).order("verified",{ascending:false}).order("name");const found=(data||[]) as Parish[];setParishes(found);if(found[0])setParishId(found[0].id);setMessage(error?"Não foi possível buscar as paróquias.":found.length?"":"Nenhuma paróquia cadastrada para esta cidade ainda.");setBusy(false);setStep(2)}
 async function finish(){if(!user)return;setBusy(true);const s=getSupabase();const preferenceMap=Object.fromEntries(topics.map(t=>[t.label,prefs.includes(t.label)]));const {error}=await s.from("profiles").upsert({id:user.id,city:city.trim(),state:state.trim().toUpperCase(),primary_parish_id:parishId||null,onboarding_completed:true,preferences:preferenceMap},{onConflict:"id"});if(!error&&parishId){await s.from("parish_members").update({is_primary:false}).eq("user_id",user.id);await s.from("parish_members").upsert({parish_id:parishId,user_id:user.id,role:"follower",is_primary:true},{onConflict:"parish_id,user_id"})}if(error){setMessage(error.message);setBusy(false);return}await refreshProfile();router.push("/")}
 if(loading||!user)return <main className="onboarding-shell"><div className="onboarding-card">Preparando sua conta…</div></main>;
 return <main className="onboarding-shell"><div className="onboarding-brand"><Link href="/" className="brand"><span className="brand-cross">✣</span><span><b>Vinde</b><small>Fé que acompanha você.</small></span></Link></div><section className="onboarding-card"><div className="onboarding-progress"><span style={{width:`${step/3*100}%`}}/></div><div className="eyebrow">PASSO {step} DE 3</div>{step===1&&<><h1>Onde sua vida de fé acontece?</h1><p className="muted">Começamos pela sua cidade para aproximar você de comunidades, missas e experiências relevantes.</p><label className="field"><span>Cidade</span><div style={{position:"relative"}}><MapPin size={18} style={{position:"absolute",left:14,top:14,color:"var(--vinde-muted)"}}/><input style={{paddingLeft:42,width:"100%"}} value={city} onChange={e=>setCity(e.target.value)}/></div></label><label className="field"><span>Estado</span><input value={state} maxLength={2} onChange={e=>setState(e.target.value.toUpperCase())}/></label></>}{step===2&&<><h1>Qual comunidade você chama de sua?</h1><p className="muted">Escolha sua paróquia principal. Ela ajuda o Vinde a mostrar horários, avisos e eventos mais próximos da sua rotina.</p>{parishes.map(p=><button type="button" className={`onboarding-choice ${parishId===p.id?"active":""}`} onClick={()=>setParishId(p.id)} key={p.id}><span><strong>{p.name}</strong><small>{p.city} • {p.state}{p.verified?" • verificada":""}</small></span><span>{parishId===p.id?"✓":""}</span></button>)}{message&&<p className="muted">{message}</p>}<button className={`onboarding-choice ${!parishId?"active":""}`} onClick={()=>setParishId("")}><span><strong>Ainda não encontrei minha paróquia</strong><small>Você pode seguir sem selecionar e escolher depois.</small></span><span>{!parishId?"✓":""}</span></button></>}{step===3&&<><h1>O que faz parte da sua caminhada?</h1><p className="muted">Escolha os assuntos que você quer encontrar com mais frequência. Isso muda suas recomendações, não limita o que você pode explorar.</p><div className="onboarding-topic-grid">{topics.map(({label,icon:Icon})=><button type="button" key={label} className={`onboarding-topic ${prefs.includes(label)?"active":""}`} onClick={()=>setPrefs(v=>v.includes(label)?v.filter(x=>x!==label):[...v,label])}><Icon size={19}/><span style={{display:"block",marginTop:8}}>{prefs.includes(label)?"✓ ":""}{label}</span></button>)}</div><p className="muted">Você poderá alterar tudo isso a qualquer momento.</p></>}<div className="actions">{step>1&&<button className="cta secondary" onClick={()=>setStep(step-1)}>Voltar</button>}{step===1?<button className="cta" disabled={busy||!city||!state} onClick={findParishes}>{busy?"Buscando…":"Encontrar comunidades"}</button>:step===2?<button className="cta" onClick={()=>setStep(3)}>Continuar</button>:<button className="cta" disabled={busy} onClick={finish}>{busy?"Salvando…":"Entrar no Vinde"}</button>}</div></section></main>;
}
