import Link from "next/link";
import {ChevronLeft,BookOpen,Heart,Headphones,CheckCircle2,Sparkles} from "lucide-react";
import {AppShell} from "@/components/AppShell";
import {DailyActions} from "@/components/DailyActions";
import {DailyHistory} from "@/components/DailyHistory";
import {GospelAudioButton} from "@/components/GospelAudioButton";
import {MomentTopActions} from "@/components/MomentTopActions";
import {getTodayDevotional} from "@/lib/data";

const bibleImage="https://images.unsplash.com/photo-1504052434569-70ad5836ab65?auto=format&fit=crop&w=1400&q=88";

export default async function Momento(){
 const d=await getTodayDevotional();const now=new Date();const dateLabel=now.toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});
 const gospel=d?.scripture_excerpt||"O texto bíblico do dia será publicado aqui com sua referência e fonte.";
 const reflection=d?.reflection||"Reserve alguns minutos para acolher a Palavra e perceber o que ela desperta em você hoje.";
 return <AppShell hideHeader><div className="moment-premium"><header className="moment-premium-top"><Link href="/" className="moment-premium-back" aria-label="Voltar"><ChevronLeft/></Link><div><span>Jornada de hoje</span><h1>Momento Diário</h1></div><MomentTopActions id={d?.id} title={d?.title||"Momento Diário"}/></header><section className="moment-premium-hero" style={{backgroundImage:`linear-gradient(180deg,rgba(48,40,32,.08),rgba(48,40,32,.68)),url(${bibleImage})`}}><div className="moment-premium-hero-copy"><span>{dateLabel.charAt(0).toUpperCase()+dateLabel.slice(1)}</span><h2>{d?.title||"Eu estou convosco todos os dias."}</h2><p>{d?.scripture_reference||"Mt 28,20"}</p><div className="moment-premium-progress"><span>Seu momento de hoje</span><strong>5 min</strong></div></div></section><nav className="moment-premium-tabs"><a className="active" href="#evangelho"><BookOpen size={15}/>Evangelho</a><a href="#reflexao"><Sparkles size={15}/>Reflexão</a><a href="#oracao"><Heart size={15}/>Oração</a><a href="#proposito"><CheckCircle2 size={15}/>Propósito</a></nav><section className="moment-premium-card gospel" id="evangelho"><div className="moment-premium-label">PALAVRA DO DIA</div><h2>Evangelho de hoje</h2><h3>{d?.scripture_reference||"Referência bíblica"}</h3><p>{gospel}</p><div className="moment-premium-audio"><Headphones size={18}/><div><strong>Ouvir o Evangelho</strong><small>Escute com calma e atenção</small></div><GospelAudioButton audioUrl={d?.audio_url} text={gospel}/></div></section><section className="moment-premium-card reflection" id="reflexao"><div className="moment-premium-icon"><Sparkles/></div><div><span>REFLEXÃO</span><h2>O que essa Palavra quer dizer para você hoje?</h2><p>{reflection}</p></div></section><section className="moment-premium-card prayer" id="oracao"><div className="moment-premium-icon"><Heart/></div><div><span>ORAÇÃO</span><h2>Fale com Deus</h2><p>{d?.prayer||"Senhor, orienta minhas escolhas e meu dia. Amém."}</p></div></section><section className="moment-premium-card purpose" id="proposito"><div className="moment-premium-icon"><CheckCircle2/></div><div><span>PROPÓSITO</span><h2>Leve a Palavra para o seu dia</h2><p>{d?.purpose||"Faça hoje um gesto concreto de escuta e cuidado."}</p></div></section><section className="moment-premium-finish"><div className="moment-premium-history"><div><span>SUA CAMINHADA</span><h2>Continue cultivando presença e constância.</h2></div><DailyHistory/></div><div className="moment-premium-actions"><DailyActions devotionalId={d?.id} title={d?.title||"Momento Diário"}/></div></section></div></AppShell>;
}
