"use client";
import {useEffect,useMemo,useState} from "react";
import {AppShell} from "@/components/AppShell";
import {getSupabase} from "@/lib/supabase";
import {HeartHandshake,ShieldCheck,MapPin,Phone,MessageCircle,Globe2,Mail,Search,ExternalLink} from "lucide-react";

const norm=(v:string)=>(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export default function Solidariedade(){
 const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{getSupabase().from("charity_institutions").select("*").eq("active",true).order("name").then(({data,error})=>{if(error)setError(error.message);setItems(data||[]);setLoading(false)})},[]);
 const list=useMemo(()=>items.filter(x=>!q||norm(`${x.name} ${x.cause||""} ${x.description||""}`).includes(norm(q))),[items,q]);
 return <AppShell><div className="page-title"><div className="eyebrow">Solidariedade em Piumhi</div><h1>Ajude quem já cuida da cidade.</h1><p className="muted">Instituições locais verificadas em fontes públicas. Antes de doar dinheiro, confirme sempre o canal oficial diretamente com a entidade.</p></div><div className="searchbox" style={{display:"flex",alignItems:"center",gap:8}}><Search size={18}/><input style={{border:0,background:"transparent",outline:"none",width:"100%"}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar instituição ou causa..."/></div>{loading?<div className="card">Carregando instituições…</div>:error?<div className="card">{error}</div>:<div className="grid">{list.map(x=><article className="card" key={x.id}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div className="iconbox"><HeartHandshake/></div>{x.verified&&<span className="tag"><ShieldCheck size={12}/> Verificada</span>}</div><h2 style={{marginTop:12}}>{x.name}</h2>{x.cause&&<p className="tiny" style={{fontWeight:800}}>{x.cause}</p>}<p className="muted">{x.description}</p>{x.address&&<p className="tiny muted" style={{display:"flex",gap:7,alignItems:"flex-start"}}><MapPin size={15}/>{x.address}</p>}<div className="actions" style={{flexWrap:"wrap"}}>{x.phone&&<a className="cta secondary" href={`tel:${x.phone}`}><Phone size={15}/> Ligar</a>}{x.whatsapp&&<a className="cta secondary" href={`https://wa.me/55${String(x.whatsapp).replace(/\D/g,"")}`} target="_blank" rel="noreferrer"><MessageCircle size={15}/> WhatsApp</a>}{x.email&&<a className="cta secondary" href={`mailto:${x.email}`}><Mail size={15}/> E-mail</a>}{x.website&&<a className="cta secondary" href={x.website} target="_blank" rel="noreferrer"><Globe2 size={15}/> Site</a>}</div>{x.donation_note&&<div className="notice" style={{marginTop:12}}><b>Como ajudar</b><p className="tiny muted">{x.donation_note}</p></div>}{x.source_url&&<a href={x.source_url} target="_blank" rel="noreferrer" className="tiny" style={{display:"inline-flex",gap:5,alignItems:"center",marginTop:10}}>Ver fonte <ExternalLink size={12}/></a>}</article>)}{!list.length&&<div className="card"><h2>Nenhuma instituição encontrada.</h2><p className="muted">Tente outro termo de busca.</p></div>}</div>}</AppShell>
}
