"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {Heart,Share2} from "lucide-react";import {useAuth} from "@/components/AuthProvider";import {getSupabase} from "@/lib/supabase";import {track} from "@/lib/analytics";
export function DailyActions({devotionalId,title}:{devotionalId?:string;title:string}){const {user,profile}=useAuth();const [done,setDone]=useState(false);const [fav,setFav]=useState(false);const [dates,setDates]=useState<string[]>([]);const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!user||!devotionalId)return;const userId=user.id;const s=getSupabase();Promise.all([s.from("devotional_completions").select("devotional_id,completed_at,daily_devotionals(devotional_date)").eq("user_id",userId).order("completed_at",{ascending:false}).limit(60),s.from("favorites").select("entity_id").eq("user_id",userId).eq("entity_type","devotional").eq("entity_id",devotionalId).maybeSingle()]).then(([a,b])=>{const rows=(a.data||[]) as any[];setDone(rows.some(x=>x.devotional_id===devotionalId));setDates(rows.map(x=>x.daily_devotionals?.devotional_date).filter(Boolean));setFav(!!b.data)});track("daily_moment_open",{entity_type:"devotional",entity_id:devotionalId,parish_id:profile?.primary_parish_id||undefined,path:"/momento"})},[user?.id,devotionalId,profile?.primary_parish_id]);
 const streak=useMemo(()=>{const unique=new Set(dates);let n=0;const d=new Date();for(let i=0;i<60;i++){const key=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);if(unique.has(key))n++;else if(i>0)break;d.setDate(d.getDate()-1)}return n},[dates]);
 if(!devotionalId)return null;if(!user)return <div className="actions left"><Link href="/entrar" className="cta">Entrar para registrar meu momento</Link></div>;const userId=user.id;
 async function complete(){setBusy(true);const s=getSupabase();const {error}=await s.from("devotional_completions").upsert({user_id:userId,devotional_id:devotionalId},{onConflict:"user_id,devotional_id"});if(!error){setDone(true);setDates(v=>[new Date().toISOString().slice(0,10),...v]);track("daily_moment_complete",{entity_type:"devotional",entity_id:devotionalId,parish_id:profile?.primary_parish_id||undefined,path:"/momento"})}setBusy(false)}
 async function favorite(){const s=getSupabase();if(fav)await s.from("favorites").delete().eq("user_id",userId).eq("entity_type","devotional").eq("entity_id",devotionalId);else await s.from("favorites").insert({user_id:userId,entity_type:"devotional",entity_id:devotionalId});setFav(!fav);track(fav?"favorite_remove":"favorite_add",{entity_type:"devotional",entity_id:devotionalId,parish_id:profile?.primary_parish_id||undefined})}
 async function share(){track("share",{entity_type:"devotional",entity_id:devotionalId,parish_id:profile?.primary_parish_id||undefined,path:"/momento"});const text=`${title} — meu Momento Diário no Ágora Fide`;if(navigator.share)await navigator.share({title,text,url:location.href});else await navigator.clipboard.writeText(`${text} ${location.href}`)}
 return <div><div className="habit-row"><span className="pill">🔥 {streak} {streak===1?"dia":"dias"} de sequência</span>{done&&<span className="tag">Momento concluído ✓</span>}</div><div className="actions left"><button className="cta" disabled={busy||done} onClick={complete}>{done?"Concluído hoje ✓":busy?"Salvando…":"Concluir momento ✓"}</button><button className="cta secondary" onClick={favorite}><Heart size={17} fill={fav?"currentColor":"none"}/>{fav?"Salvo":"Favoritar"}</button><button className="cta secondary" onClick={share}><Share2 size={17}/>Compartilhar</button></div></div>
}
