// @ts-nocheck
"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AuthGuard} from "@/components/AuthGuard";
import {useAuth} from "@/components/AuthProvider";
import {getSupabase} from "@/lib/supabase";

type Mode="paroquia"|"horarios"|"avisos"|"eventos"|"campanhas";
const week=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const names:Record<string,string>={confession:"Confissão",adoration:"Adoração",celebration:"Celebração especial",secretary:"Secretaria"};

export function ParishAdminManager({mode}:{mode:Mode}){
 const {user}=useAuth();
 const [parishId,setParishId]=useState<string|null>(null),[parish,setParish]=useState<any>(null),[items,setItems]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 const [form,setForm]=useState<any>({weekday:"0",starts_at:"19:00",ends_at:"",label:"",service_type:"confession",title:"",body:"",description:"",location:"",event_date:"",goal:""});
 async function refresh(id:string){const s=getSupabase();if(mode==="horarios"){const a=await s.from("mass_schedules").select("*").eq("parish_id",id).order("weekday").order("starts_at");const b=await s.from("parish_service_schedules").select("*").eq("parish_id",id).order("service_type").order("weekday");setItems(a.data||[]);setServices(b.data||[])}if(mode==="avisos"){const r=await s.from("parish_posts").select("*").eq("parish_id",id).order("created_at",{ascending:false});setItems(r.data||[])}if(mode==="eventos"){const r=await s.from("events").select("*").eq("parish_id",id).order("starts_at");setItems(r.data||[])}if(mode==="campanhas"){const r=await s.from("campaigns").select("*").eq("parish_id",id).order("created_at",{ascending:false});setItems(r.data||[])}}
 useEffect(()=>{if(!user)return;const run=async()=>{const s=getSupabase();const r=await s.from("parish_members").select("parish_id").eq("user_id",user.id).in("role",["admin","editor"]).limit(1).maybeSingle();const id=r.data?.parish_id;if(!id){setBusy(false);return}setParishId(id);const p=await s.from("parishes").select("*").eq("id",id).maybeSingle();setParish(p.data);await refresh(id);setBusy(false)};void run()},[user,mode]);
 const done=async(error:any,text:string)=>{setMessage(error?`Erro: ${error.message}`:text);if(!error&&parishId)await refresh(parishId)};
 const del=async(table:string,id:string)=>{if(!confirm("Excluir este item?"))return;const r=await getSupabase().from(table).delete().eq("id",id);await done(r.error,"Item excluído.")};
 const saveParish=async(e:any)=>{e.preventDefault();if(!parishId||!parish)return;const payload={name:parish.name,city:parish.city,state:parish.state,address:parish.address||null,phone:parish.phone||null,whatsapp:parish.whatsapp||null,instagram:parish.instagram||null,website:parish.website||null,photo_url:parish.photo_url||null,description:parish.description||null,secretary_hours:parish.secretary_hours||null,maps_url:parish.maps_url||null};const r=await getSupabase().from("parishes").update(payload).eq("id",parishId);setMessage(r.error?`Erro: ${r.error.message}`:"Dados salvos com sucesso.")};
 const submit=async(e:any,kind:string)=>{e.preventDefault();if(!parishId)return;const s=getSupabase();let r:any;if(kind==="mass")r=await s.from("mass_schedules").insert({parish_id:parishId,weekday:Number(form.weekday),starts_at:form.starts_at,label:form.label||null,active:true});else if(kind==="service")r=await s.from("parish_service_schedules").insert({parish_id:parishId,service_type:form.service_type,weekday:Number(form.weekday),starts_at:form.starts_at||null,ends_at:form.ends_at||null,label:form.label||null,active:true});else if(kind==="post")r=await s.from("parish_posts").insert({parish_id:parishId,title:form.title,body:form.body||null,published_at:new Date().toISOString()});else if(kind==="event")r=await s.from("events").insert({parish_id:parishId,title:form.title,description:form.description||null,starts_at:new Date(form.event_date).toISOString(),location:form.location||null,status:"published",price_cents:0});else r=await s.from("campaigns").insert({parish_id:parishId,title:form.title,description:form.description||null,goal_cents:form.goal?Math.round(Number(form.goal)*100):null,status:"published",verified:false});await done(r.error,"Salvo com sucesso.")};
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 return <AuthGuard mode="parish"><main className="shell"><div className="topbar"><Link href="/admin" className="brand"><span><b>Ágora Fide</b><small>PAINEL PAROQUIAL</small></span></Link><Link href="/admin" className="avatar">←</Link></div>{busy?<div className="card">Carregando…</div>:!parishId?<div className="card">Nenhuma paróquia administrável encontrada.</div>:<><div className="page-title"><div className="eyebrow">{parish?.name}</div><h1>{mode==="paroquia"?"Dados da paróquia":mode==="horarios"?"Horários":mode==="avisos"?"Avisos oficiais":mode==="eventos"?"Eventos":"Campanhas"}</h1></div>{message&&<div className="notice-inline">{message}</div>}
 {mode==="paroquia"&&parish&&<form className="card" onSubmit={saveParish}>{[["name","Nome"],["description","Descrição"],["address","Endereço"],["phone","Telefone"],["whatsapp","WhatsApp"],["instagram","Instagram"],["website","Site"],["photo_url","URL da foto"],["secretary_hours","Horário da secretaria"],["maps_url","Link do mapa"],["city","Cidade"],["state","Estado"]].map(([k,l])=><label className="field" key={k}>{l}{k==="description"?<textarea className="searchbox" value={parish[k]||""} onChange={e=>setParish({...parish,[k]:e.target.value})}/>:<input value={parish[k]||""} onChange={e=>setParish({...parish,[k]:e.target.value})}/>}</label>)}<button className="cta">Salvar alterações</button></form>}
 {mode==="horarios"&&<><form className="card" onSubmit={e=>submit(e,"mass")}><h2>Nova missa</h2><label className="field">Dia<select value={form.weekday} onChange={e=>set("weekday",e.target.value)}>{week.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label><label className="field">Horário<input type="time" value={form.starts_at} onChange={e=>set("starts_at",e.target.value)}/></label><label className="field">Descrição<input value={form.label} onChange={e=>set("label",e.target.value)}/></label><button className="cta">Adicionar missa</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{week[x.weekday]} · {String(x.starts_at).slice(0,5)}</b><small>{x.label}</small></span><button className="cta secondary" onClick={()=>del("mass_schedules",x.id)}>Excluir</button></div>)}</div><form className="card" style={{marginTop:14}} onSubmit={e=>submit(e,"service")}><h2>Confissão, adoração e outros</h2><label className="field">Tipo<select value={form.service_type} onChange={e=>set("service_type",e.target.value)}>{Object.keys(names).map(k=><option key={k} value={k}>{names[k]}</option>)}</select></label><label className="field">Dia<select value={form.weekday} onChange={e=>set("weekday",e.target.value)}>{week.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label><label className="field">Início<input type="time" value={form.starts_at} onChange={e=>set("starts_at",e.target.value)}/></label><label className="field">Fim<input type="time" value={form.ends_at} onChange={e=>set("ends_at",e.target.value)}/></label><label className="field">Observação<input value={form.label} onChange={e=>set("label",e.target.value)}/></label><button className="cta">Adicionar horário</button></form><div className="card list" style={{marginTop:10}}>{services.map(x=><div className="row" key={x.id}><span><b>{names[x.service_type]} · {week[x.weekday]}</b><small>{String(x.starts_at||"").slice(0,5)} {x.ends_at?`– ${String(x.ends_at).slice(0,5)}`:""} {x.label||""}</small></span><button className="cta secondary" onClick={()=>del("parish_service_schedules",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="avisos"&&<><form className="card" onSubmit={e=>submit(e,"post")}><h2>Novo aviso</h2><input className="searchbox" placeholder="Título" value={form.title} onChange={e=>set("title",e.target.value)}/><textarea className="searchbox" placeholder="Texto do aviso" value={form.body} onChange={e=>set("body",e.target.value)}/><button className="cta">Publicar aviso</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{x.body}</small></span><button className="cta secondary" onClick={()=>del("parish_posts",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="eventos"&&<><form className="card" onSubmit={e=>submit(e,"event")}><h2>Novo evento</h2><input className="searchbox" placeholder="Título" value={form.title} onChange={e=>set("title",e.target.value)}/><input className="searchbox" type="datetime-local" value={form.event_date} onChange={e=>set("event_date",e.target.value)}/><input className="searchbox" placeholder="Local" value={form.location} onChange={e=>set("location",e.target.value)}/><textarea className="searchbox" placeholder="Descrição" value={form.description} onChange={e=>set("description",e.target.value)}/><button className="cta">Publicar evento</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{new Date(x.starts_at).toLocaleString("pt-BR")}</small></span><button className="cta secondary" onClick={()=>del("events",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="campanhas"&&<><form className="card" onSubmit={e=>submit(e,"campaign")}><h2>Nova campanha</h2><input className="searchbox" placeholder="Título" value={form.title} onChange={e=>set("title",e.target.value)}/><input className="searchbox" type="number" placeholder="Meta em R$" value={form.goal} onChange={e=>set("goal",e.target.value)}/><textarea className="searchbox" placeholder="História e objetivo" value={form.description} onChange={e=>set("description",e.target.value)}/><button className="cta">Publicar campanha</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{x.status}</small></span><button className="cta secondary" onClick={()=>del("campaigns",x.id)}>Excluir</button></div>)}</div></>}
 </>}</main></AuthGuard>}
