"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {AuthGuard} from "@/components/AuthGuard";
import {useAuth} from "@/components/AuthProvider";
import {getSupabase} from "@/lib/supabase";

type Mode="paroquia"|"horarios"|"avisos"|"eventos"|"campanhas";
const week=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const serviceNames:any={confession:"Confissão",adoration:"Adoração",celebration:"Celebração especial",secretary:"Secretaria"};

export function ParishAdminManager({mode}:{mode:Mode}){
 const {user}=useAuth(); const [parishId,setParishId]=useState<string|null>(null); const [parish,setParish]=useState<any>(null); const [items,setItems]=useState<any[]>([]); const [services,setServices]=useState<any[]>([]); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const [form,setForm]=useState<any>({weekday:0,starts_at:"19:00",label:"",service_type:"confession",ends_at:"",title:"",body:"",description:"",location:"",event_date:"",goal:""});
 useEffect(()=>{if(!user)return;(async()=>{const s=getSupabase();const {data:m}=await s.from("parish_members").select("parish_id,role").eq("user_id",user.id).in("role",["admin","editor"]).limit(1).maybeSingle();if(!m){setBusy(false);return}setParishId(m.parish_id);const {data:p}=await s.from("parishes").select("*").eq("id",m.parish_id).maybeSingle();setParish(p);await load(m.parish_id);setBusy(false)})()},[user,mode]);
 async function load(id:string){const s=getSupabase();if(mode==="horarios"){const [{data:a},{data:b}]=await Promise.all([s.from("mass_schedules").select("*").eq("parish_id",id).order("weekday").order("starts_at"),s.from("parish_service_schedules").select("*").eq("parish_id",id).order("service_type").order("weekday")]);setItems(a||[]);setServices(b||[])}else if(mode==="avisos"){const {data}=await s.from("parish_posts").select("*").eq("parish_id",id).order("created_at",{ascending:false});setItems(data||[])}else if(mode==="eventos"){const {data}=await s.from("events").select("*").eq("parish_id",id).order("starts_at");setItems(data||[])}else if(mode==="campanhas"){const {data}=await s.from("campaigns").select("*").eq("parish_id",id).order("created_at",{ascending:false});setItems(data||[])}}
 async function saveParish(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);setMessage("");const s=getSupabase();const payload={name:parish.name,city:parish.city,state:parish.state,address:parish.address||null,phone:parish.phone||null,whatsapp:parish.whatsapp||null,instagram:parish.instagram||null,website:parish.website||null,photo_url:parish.photo_url||null,description:parish.description||null,secretary_hours:parish.secretary_hours||null,maps_url:parish.maps_url||null};const {error}=await s.from("parishes").update(payload).eq("id",parishId);setMessage(error?`Erro: ${error.message}`:"Dados salvos com sucesso.");setSaving(false)}
 async function addMass(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);const s=getSupabase();const {error}=await s.from("mass_schedules").insert({parish_id:parishId,weekday:Number(form.weekday),starts_at:form.starts_at,label:form.label||null,active:true});setMessage(error?`Erro: ${error.message}`:"Horário adicionado.");if(!error)await load(parishId);setSaving(false)}
 async function addService(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);const s=getSupabase();const {error}=await s.from("parish_service_schedules").insert({parish_id:parishId,service_type:form.service_type,weekday:Number(form.weekday),starts_at:form.starts_at||null,ends_at:form.ends_at||null,label:form.label||null,active:true});setMessage(error?`Erro: ${error.message}`:"Horário especial adicionado.");if(!error)await load(parishId);setSaving(false)}
 async function addPost(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);const s=getSupabase();const {error}=await s.from("parish_posts").insert({parish_id:parishId,title:form.title,body:form.body||null,published_at:new Date().toISOString()});setMessage(error?`Erro: ${error.message}`:"Aviso publicado.");if(!error){setForm({...form,title:"",body:""});await load(parishId)}setSaving(false)}
 async function addEvent(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);const s=getSupabase();const {error}=await s.from("events").insert({parish_id:parishId,title:form.title,description:form.description||null,starts_at:new Date(form.event_date).toISOString(),location:form.location||null,status:"published",price_cents:0});setMessage(error?`Erro: ${error.message}`:"Evento publicado.");if(!error)await load(parishId);setSaving(false)}
 async function addCampaign(e:FormEvent){e.preventDefault();if(!parishId)return;setSaving(true);const s=getSupabase();const cents=form.goal?Math.round(Number(String(form.goal).replace(",","."))*100):null;const {error}=await s.from("campaigns").insert({parish_id:parishId,title:form.title,description:form.description||null,goal_cents:cents,status:"published",verified:false});setMessage(error?`Erro: ${error.message}`:"Campanha publicada.");if(!error)await load(parishId);setSaving(false)}
 async function remove(table:string,id:string){if(!parishId||!confirm("Excluir este item?"))return;const {error}=await getSupabase().from(table).delete().eq("id",id);setMessage(error?`Erro: ${error.message}`:"Item excluído.");if(!error)await load(parishId)}
 const input=(key:string,placeholder:string,type="text")=><input className="searchbox" type={type} value={form[key]||""} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/>;
 return <AuthGuard mode="parish"><main className="shell"><div className="topbar"><Link href="/admin" className="brand"><span><b>Ágora Fide</b><small>PAINEL PAROQUIAL</small></span></Link><Link href="/admin" className="avatar">←</Link></div>{busy?<div className="card">Carregando…</div>:!parishId?<div className="card">Nenhuma paróquia administrável encontrada.</div>:<><div className="page-title"><div className="eyebrow">{parish?.name}</div><h1>{mode==="paroquia"?"Dados da paróquia":mode==="horarios"?"Horários":mode==="avisos"?"Avisos oficiais":mode==="eventos"?"Eventos":"Campanhas"}</h1></div>{message&&<div className="notice-inline">{message}</div>}
 {mode==="paroquia"&&parish&&<form className="card" onSubmit={saveParish}><label className="field">Nome<input value={parish.name||""} onChange={e=>setParish({...parish,name:e.target.value})}/></label><label className="field">Descrição<textarea value={parish.description||""} onChange={e=>setParish({...parish,description:e.target.value})}/></label>{[["address","Endereço"],["phone","Telefone"],["whatsapp","WhatsApp"],["instagram","Instagram"],["website","Site"],["photo_url","URL da foto"],["secretary_hours","Horário da secretaria"],["maps_url","Link do mapa"]].map(([k,l])=><label className="field" key={k}>{l}<input value={parish[k]||""} onChange={e=>setParish({...parish,[k]:e.target.value})}/></label>)}<div className="grid two"><label className="field">Cidade<input value={parish.city||""} onChange={e=>setParish({...parish,city:e.target.value})}/></label><label className="field">Estado<input value={parish.state||""} onChange={e=>setParish({...parish,state:e.target.value})}/></label></div><button className="cta" disabled={saving}>Salvar alterações</button></form>}
 {mode==="horarios"&&<><form className="card" onSubmit={addMass}><h2>Nova missa</h2><label className="field">Dia<select value={form.weekday} onChange={e=>setForm({...form,weekday:e.target.value})}>{week.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label>{input("starts_at","Horário","time")}{input("label","Ex.: Missa da família")}<button className="cta" disabled={saving}>Adicionar missa</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{week[x.weekday]} · {String(x.starts_at).slice(0,5)}</b><small>{x.label}</small></span><button className="cta secondary" onClick={()=>remove("mass_schedules",x.id)}>Excluir</button></div>)}</div><form className="card" style={{marginTop:16}} onSubmit={addService}><h2>Confissão, adoração e outros</h2><label className="field">Tipo<select value={form.service_type} onChange={e=>setForm({...form,service_type:e.target.value})}>{Object.entries(serviceNames).map(([k,v])=><option key={k} value={k}>{String(v)}</option>)}</select></label><label className="field">Dia<select value={form.weekday} onChange={e=>setForm({...form,weekday:e.target.value})}>{week.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label>{input("starts_at","Início","time")}{input("ends_at","Fim","time")}{input("label","Observação")}<button className="cta">Adicionar horário</button></form><div className="card list" style={{marginTop:10}}>{services.map(x=><div className="row" key={x.id}><span><b>{serviceNames[x.service_type]} · {week[x.weekday]}</b><small>{String(x.starts_at||"").slice(0,5)} {x.ends_at?`– ${String(x.ends_at).slice(0,5)}`:""} {x.label||""}</small></span><button className="cta secondary" onClick={()=>remove("parish_service_schedules",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="avisos"&&<><form className="card" onSubmit={addPost}><h2>Novo aviso</h2>{input("title","Título")}<textarea className="searchbox" value={form.body||""} placeholder="Texto do aviso" onChange={e=>setForm({...form,body:e.target.value})}/><button className="cta">Publicar aviso</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{x.body}</small></span><button className="cta secondary" onClick={()=>remove("parish_posts",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="eventos"&&<><form className="card" onSubmit={addEvent}><h2>Novo evento</h2>{input("title","Título")}{input("event_date","Data e hora","datetime-local")}{input("location","Local")}<textarea className="searchbox" value={form.description||""} placeholder="Descrição" onChange={e=>setForm({...form,description:e.target.value})}/><button className="cta">Publicar evento</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{new Date(x.starts_at).toLocaleString("pt-BR")} · {x.location}</small></span><button className="cta secondary" onClick={()=>remove("events",x.id)}>Excluir</button></div>)}</div></>}
 {mode==="campanhas"&&<><form className="card" onSubmit={addCampaign}><h2>Nova campanha</h2>{input("title","Título")}{input("goal","Meta em R$","number")}<textarea className="searchbox" value={form.description||""} placeholder="História e objetivo" onChange={e=>setForm({...form,description:e.target.value})}/><button className="cta">Publicar campanha</button></form><div className="card list" style={{marginTop:10}}>{items.map(x=><div className="row" key={x.id}><span><b>{x.title}</b><small>{x.status} · meta {x.goal_cents?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(x.goal_cents/100):"não definida"}</small></span><button className="cta secondary" onClick={()=>remove("campaigns",x.id)}>Excluir</button></div>)}</div></>}
 </>}</main></AuthGuard>}
