"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {Heart,Share2,Minus,Plus,ShoppingCart,Truck,LockKeyhole,RotateCcw,CheckCircle2,PackageCheck,ArrowRight,ChevronRight} from "lucide-react";

type P={id:string;name:string;description?:string|null;price_cents:number;stock:number;image_url?:string|null;images?:string[]|null;category?:string|null};
const KEY="agora-fide-cart";
const brl=(c:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(c/100);
const countCart=()=>{try{return (JSON.parse(localStorage.getItem(KEY)||"[]") as any[]).reduce((n,x)=>n+(Number(x.quantity)||0),0)}catch{return 0}};

export function ProductReference({p}:{p:P}){
 const gallery=useMemo(()=>Array.from(new Set([...(p.images||[]),...(p.image_url?[p.image_url]:[])].filter(Boolean))),[p.images,p.image_url]);
 const [qty,setQty]=useState(1),[fav,setFav]=useState(false),[added,setAdded]=useState(false),[cartCount,setCartCount]=useState(0),[selectedImage,setSelectedImage]=useState(gallery[0]||"");
 useEffect(()=>{const sync=()=>setCartCount(countCart());sync();window.addEventListener("agora-cart",sync);window.addEventListener("storage",sync);return()=>{window.removeEventListener("agora-cart",sync);window.removeEventListener("storage",sync)}},[]);
 function add(){const current:any[]=JSON.parse(localStorage.getItem(KEY)||"[]");const found=current.find(x=>x.id===p.id);if(found)found.quantity+=qty;else current.push({id:p.id,name:p.name,price_cents:p.price_cents,quantity:qty,image_url:p.image_url});localStorage.setItem(KEY,JSON.stringify(current));window.dispatchEvent(new Event("agora-cart"));setAdded(true)}
 async function share(){const data={title:p.name,text:`Veja ${p.name} no Vinde`,url:location.href};if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(location.href)}
 const installment=brl(Math.ceil(p.price_cents/3));
 return <div className="product-ref">
  <nav className="product-breadcrumb" aria-label="Breadcrumb"><Link href="/loja">Loja</Link><ChevronRight/><Link href={p.category?`/loja?categoria=${encodeURIComponent(p.category)}`:"/loja"}>{p.category||"Curadoria"}</Link><ChevronRight/><span>{p.name}</span></nav>
  <section className="product-gallery">
   <div className="product-ref-image"><div className="product-ref-badge">{p.category||"Seleção Vinde"}</div><div className="product-ref-tools"><Link href="/carrinho" className="product-cart-mini" aria-label={`Abrir carrinho com ${cartCount} itens`}><ShoppingCart/>{cartCount>0&&<span>{cartCount>99?"99+":cartCount}</span>}</Link><button onClick={()=>setFav(!fav)} aria-label="Favoritar produto"><Heart fill={fav?"currentColor":"none"}/></button><button onClick={share} aria-label="Compartilhar produto"><Share2/></button></div>{selectedImage?<img src={selectedImage} alt={p.name} loading="eager"/>:<div className="product-ref-placeholder">✣</div>}</div>
   {gallery.length>0&&<div className="product-thumbs" aria-label="Imagens do produto">{gallery.map((src,i)=><button key={`${src}-${i}`} type="button" className={selectedImage===src?"active":""} onClick={()=>setSelectedImage(src)} aria-label={`Ver imagem ${i+1} de ${gallery.length}`}><img src={src} alt=""/></button>)}</div>}
  </section>
  <section className="product-sheet"><div className="product-kicker">Vendido por Ágora Fide</div><h1>{p.name}</h1><div className="product-price-row"><div><div className="product-price-ref">{brl(p.price_cents)}</div><p>ou 3x de {installment} sem juros</p></div></div><div className={p.stock>0?"product-stock-line ok":"product-stock-line"}><CheckCircle2 size={16}/><span>{p.stock>0?`Em estoque · ${p.stock} ${p.stock===1?"unidade disponível":"unidades disponíveis"}`:"Indisponível no momento"}</span></div><p className="product-desc">{p.description||"Produto selecionado para acompanhar sua fé no dia a dia."}</p><div className="product-benefits"><div><Truck/><span><strong>Entrega pelo Vinde</strong><small>Frete calculado no checkout</small></span></div><div><LockKeyhole/><span><strong>Compra protegida</strong><small>Pagamento seguro dentro do app</small></span></div><div><RotateCcw/><span><strong>Compra tranquila</strong><small>Política de troca informada no checkout</small></span></div></div><div className="product-buybox"><div className="product-buybox-head"><div><span>Quantidade</span><small>Escolha quantas unidades deseja</small></div><div className="product-qty"><button onClick={()=>setQty(q=>Math.max(1,q-1))} aria-label="Diminuir quantidade" disabled={qty<=1}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(q=>Math.min(Math.max(p.stock,1),q+1))} aria-label="Aumentar quantidade" disabled={p.stock<=0||qty>=p.stock}><Plus/></button></div></div><button className="product-cart" onClick={add} disabled={p.stock===0}><ShoppingCart/>{p.stock===0?"Indisponível":added?"Adicionado ao carrinho ✓":"Adicionar ao carrinho"}</button>{cartCount>0&&<Link href="/carrinho" className="product-view-cart">Ver carrinho <span>{cartCount} {cartCount===1?"item":"itens"}</span><ArrowRight/></Link>}<div className="product-secure"><PackageCheck/> Compra, pagamento e acompanhamento dentro do Vinde.</div></div></section>
 </div>
}
