"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {AppShell} from "@/components/AppShell";
import {useAuth} from "@/components/AuthProvider";
import {getSupabase} from "@/lib/supabase";
import {ClipboardList,Clock3,CheckCircle2,FileText,CalendarDays,ArrowLeft} from "lucide-react";
import styles from "../vida-paroquial.module.css";

const labels:Record<string,string>={received:"Recebida",in_review:"Em análise",awaiting_documents:"Aguardando documentos",scheduled:"Agendada",completed:"Concluída",cancelled:"Cancelada"};
export default function Solicitacoes(){const {user,loading:authLoading}=useAuth();const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{if(authLoading)return;if(!user){setLoading(false);return}(async()=>{const {data}=await getSupabase().from("parish_service_requests").select("id,status,preferred_date,notes,created_at,parish_services(title,slug),parishes(name)").eq("user_id",user.id).order("created_at",{ascending:false});setItems(data||[]);setLoading(false)})()},[user?.id,authLoading]);return <AppShell><div className={styles.page}><section className={styles.hero}><span className={styles.eyebrow}>MINHA IGREJA</span><h1>Minhas solicitações</h1><p>Acompanhe pedidos enviados para a secretaria da sua comunidade.</p></section>{loading?<div className={styles.note}>Carregando solicitações…</div>:!user?<div className={styles.note}><strong>Entre na sua conta</strong><p>Você precisa estar conectado para acompanhar solicitações.</p><Link href="/entrar">Entrar</Link></div>:items.length?<div className={styles.requestList}>{items.map(x=><article className={styles.requestCard} key={x.id}><div className={styles.requestIcon}>{x.status==="completed"?<CheckCircle2/>:x.status==="scheduled"?<CalendarDays/>:x.status==="awaiting_documents"?<FileText/>:<ClipboardList/>}</div><div><small>{x.parishes?.name||"Paróquia"}</small><strong>{x.parish_services?.title||"Atendimento paroquial"}</strong><span><Clock3 size={12}/>{new Date(x.created_at).toLocaleDateString("pt-BR")}</span>{x.preferred_date&&<span>Preferência: {new Date(`${x.preferred_date}T12:00:00`).toLocaleDateString("pt-BR")}</span>}</div><b data-status={x.status}>{labels[x.status]||x.status}</b></article>)}</div>:<div className={styles.note}><strong>Nenhuma solicitação ainda</strong><p>Quando você iniciar um pedido de Batismo, Matrimônio, Catequese ou outro serviço, ele aparecerá aqui.</p></div>}<Link href="/igreja/secretaria" className={styles.back}><ArrowLeft size={15}/>Voltar para Secretaria</Link></div></AppShell>}
